services:
  kwakagent42:
    image: "${DOCKER_IMAGE}"
    container_name: kwakagent42
    restart: always
    env_file:
      - .env
    volumes:
      - /var/run/tappd.sock:/var/run/tappd.sock
      - eliza:/app/packages/client-twitter/src/tweetcache
      - eliza:/app/db.sqlite
volumes:
    eliza: