services:
  kwakagent42:
    image: kwakagent42v3
    container_name: kwakagent42
    restart: always
    env_file:
      - .env
    volumes:
      - /var/run/tappd.sock:/var/run/tappd.sock
      - eliza_tweetcache:/app/packages/client-twitter/src/tweetcache
      - eliza_db:/app/db.sqlite
volumes:
  eliza_tweetcache:
  eliza_db:
