name: Deploy Kwak Agent 42 and Laïka on VPS

on:
  push:
    branches:
      - kwakagent
      - test_multiple_agents
      - none
  pull_request:
    branches:
      - kwakagent
      - test_multiple_agents
      - none
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Check-out du code du dépôt
      - name: Checkout repository
        uses: actions/checkout@v3

      # Login to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/kwakagent42:latest .

      # Push Docker image to Docker Hub
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/kwakagent42:latest

      # Set up SSH key for remote access
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # Copie le docker-compose.yml sur le VPS
      - name: Copy docker-compose.yml to VPS
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > /tmp/id_rsa
          chmod 600 /tmp/id_rsa
          scp -o StrictHostKeyChecking=no -i /tmp/id_rsa -P ${{ secrets.PORT }} ./docker-compose.yaml octo@${{ secrets.VPS_IP }}:/home/octo/kwakagent42/

      - name: Deploy on VPS
        run: |
          # Pull the latest Docker image from Docker Hub
          ssh -o StrictHostKeyChecking=no -i /tmp/id_rsa -p ${{ secrets.PORT }} octo@${{ secrets.VPS_IP }} "cd /home/octo/kwakagent42 && docker-compose pull"
          
          # Stop kwakagent42 service only
          ssh -o StrictHostKeyChecking=no -i /tmp/id_rsa -p ${{ secrets.PORT }} octo@${{ secrets.VPS_IP }} "cd /home/octo/kwakagent42 && docker-compose stop kwakagent42"
          
          # Start the updated kwakagent42 service using the new image
          ssh -o StrictHostKeyChecking=no -i /tmp/id_rsa -p ${{ secrets.PORT }} octo@${{ secrets.VPS_IP }} "cd /home/octo/kwakagent42 && docker-compose up --build -d kwakagent42"